name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'colorado_river/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'colorado_river/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/colorado_river
    defaults:
      run:
        working-directory: colorado_river
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q


